### ISSUE TITLE
Valid estimateGas call crashes testrpc

### ISSUE THREAD

**Issue by area** [ethereumjs/testrpc#16]
I've been trying to use the newly released version of `testrpc`, but the behaviour of `estimateGas` has changed with the release compared to my original pull request. When an address without enough balance to fund the transaction tries to estimate the gas, `testrpc` crashes:

```
        var result = ethUtil.addHexPrefix(results.gasUsed.toString('hex'))
                                                         ^

TypeError: Cannot read property 'toString' of undefined
    at <snip>/testrpc/node_modules/web3-provider-engine/subproviders/vm.js:56:58
```

The value of `results` is:

    { error: [Error: sender doesn't have enough funds to send tx. The upfront cost is: 3141592 and the senders account only has: 0] }

In `geth` (which I am using as the arbiter of 'valid'), the call succeeds. It seems this is due to offloading the handling of `estimateGas` and `ethCall` into `web3-provider-engine`.

Further digging while writing this issue appears to suggest you are probably already aware of this (I presume you're the tim in https://github.com/ethereumjs/ethereumjs-vm/issues/41, which is certainly related) but I've opened this anyway in case you're not aware of the crashing side of it.

**Comment by tcoulter** [comment]
Good catch. I had forgotten about this case. I'll work on that today.

**Comment by tcoulter** [comment]
There's got to be another wrinkle to this one. I just wrote this test, which passes:

```
it("should be able to estimate gas from an account not within the accounts list (eth_estimateGas)", function(done){
  var tx_data = contract.transaction_data;
  tx_data.to = contractAddress;
  tx_data.from = "0x1234567890123456789012345678901234567890";;

  var starting_block_number = null;

  web3.eth.estimateGas(tx_data, function(err, result) 
    if (err) return done(err);
    assert.equal(result, 26585);
    done();
  });
});
```

Notice the from address, and how that's not returned via eth_accounts. That said, I can still switch things over to `runCall` vs `runTx` to be absolutely sure.

**Comment by area** [comment]
Hm, interesting, I'll try and narrow it down.

**Comment by tcoulter** [comment]
I'm going to work on switching to `runCall` anyway. Perhaps once I'm finished I can get you to test it.

**Comment by area** [comment]
If you set `tx_data.gasPrice` to be e.g. `0x1`, then the test fails.

**Comment by tcoulter** [comment]
Ah ha! Superb, thanks!

**Comment by tcoulter** [comment]
Will be fixed once this PR is merged: https://github.com/MetaMask/provider-engine/pull/38

**Comment by area** [comment]
Great, thanks for the quick turnaround.

**Comment by area** [comment]
Can the version of provider-engine be bumped now it's been fixed there?

**Comment by tcoulter** [comment]
You mean the testrpc, I assume. The provider engine has been bumped. The
testrpc likely will get bumped tomorrow.

**Comment by area** [comment]
I meant the version of the provider-engine in `package.json`

**Comment by tcoulter** [comment]
TestRPC bumped to v1.1.0 with the correct dependencies. Thanks for your patience!
